language: go

go:
- 1.11.x

env:
- GO111MODULE=on

install:
- export GO111MODULE=on
- go mod download

script:
- go test -v -coverprofile=cover.out

after_success:
- bash <(curl -s https://codecov.io/bash) -f cover.out
